import {MigrationInterface, QueryRunner} from "typeorm";

export class JobsMigration1628809102134 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (1, 1, 'Software Consultant', 'Bosilovo', 'Pilot', '$20139.96', '8/2/2021', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '5/18/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (2, 1, 'Internal Auditor', 'Siedlce', 'Diamante', '$24467.78', '11/15/2020', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '4/23/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (3, 1, 'VP Sales', 'Huanglian', 'S8', '$15178.89', '9/3/2020', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '1/1/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (4, 1, 'Staff Accountant I', 'Rincón', 'B-Series Plus', '$24258.86', '3/2/2021', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '7/7/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (5, 1, 'VP Product Management', 'Vitali', 'TSX', '$12013.25', '10/8/2020', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '12/15/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (6, 1, 'Computer Systems Analyst II', 'Adela', '3500 Club Coupe', '$15275.02', '12/5/2020', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '5/23/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (7, 1, 'Project Manager', 'Dogbo', 'A4', '$10513.66', '6/3/2021', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '8/30/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (8, 1, 'Nuclear Power Engineer', 'Taihe Chengguanzhen', 'DB9', '$16199.59', '6/1/2021', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '4/3/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (9, 1, 'Help Desk Operator', 'Chernyshevsk', 'Commander', '$21201.78', '7/22/2021', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '7/22/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (10, 1, 'Administrative Officer', 'Almaguer', 'Countach', '$12009.94', '5/2/2021', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '1/9/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (11, 1, 'VP Marketing', 'Aconibe', 'Tribeca', '$29321.47', '5/11/2021', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '11/2/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (12, 1, 'Account Representative II', 'Phaya Thai', 'Galant', '$10062.97', '9/13/2020', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '8/19/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (13, 1, 'Programmer Analyst IV', 'Budenovetc', 'Continental Mark VII', '$12673.29', '7/20/2021', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/100x100.png/dddddd/000000', '12/2/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (14, 1, 'Human Resources Assistant III', 'Ecilda Paullier', 'GTI', '$15494.97', '8/24/2021', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'http://dummyimage.com/100x100.png/dddddd/000000', '5/11/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (15, 1, 'Geological Engineer', 'Glugur Tengah', 'Sonata', '$20687.76', '2/14/2021', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'http://dummyimage.com/100x100.png/dddddd/000000', '11/11/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (16, 1, 'Recruiter', 'Nonggunong', 'M6', '$17347.24', '1/23/2021', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'http://dummyimage.com/100x100.png/dddddd/000000', '4/23/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (17, 1, 'Accounting Assistant III', 'Ni’ao', 'LeSabre', '$24294.65', '6/10/2021', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '10/21/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (18, 1, 'Associate Professor', 'Babakan Baru', '911', '$12533.65', '7/29/2021', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '7/14/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (19, 1, 'Recruiting Manager', 'Soly', 'Galant', '$22525.54', '4/21/2021', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '1/14/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (20, 1, 'Information Systems Manager', 'Angoulême', 'Cooper Clubman', '$10970.25', '9/7/2020', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '3/22/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (21, 1, 'VP Sales', 'Bunda', 'Ram', '$24273.59', '12/22/2020', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '7/4/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (22, 1, 'Speech Pathologist', 'Naval', 'E350', '$19008.45', '6/19/2021', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 'http://dummyimage.com/100x100.png/dddddd/000000', '4/28/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (23, 1, 'Geologist III', 'Halinów', 'Sierra 1500', '$14760.58', '4/16/2021', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', 'http://dummyimage.com/100x100.png/dddddd/000000', '1/26/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (24, 1, 'Chemical Engineer', 'Tinta', 'Previa', '$25216.53', '1/25/2021', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '9/25/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (25, 1, 'VP Marketing', 'Thoen', 'Dakota', '$29903.07', '9/18/2021', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '1/31/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (26, 1, 'Teacher', 'Xiluo', 'Highlander', '$12673.27', '3/10/2021', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'http://dummyimage.com/100x100.png/dddddd/000000', '12/26/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (27, 1, 'Cost Accountant', 'Tuluá', 'Land Cruiser', '$26484.62', '7/30/2021', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '3/17/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (28, 1, 'Payment Adjustment Coordinator', 'Berlin', '330', '$27461.89', '10/19/2020', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '11/2/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (29, 1, 'Accountant I', 'Intipucá', 'Crown Victoria', '$15083.39', '4/6/2021', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '3/5/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (30, 1, 'Staff Scientist', 'Bosanski Brod', 'Frontier', '$15520.04', '7/21/2021', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/100x100.png/dddddd/000000', '9/23/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (31, 1, 'Civil Engineer', 'Lom Sak', 'Esteem', '$27142.69', '9/16/2021', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '1/6/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (32, 1, 'GIS Technical Architect', 'Killorglin', 'Town Car', '$17771.46', '9/15/2020', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '8/4/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (33, 1, 'Research Associate', 'Zhuyang', 'Insight', '$23002.53', '9/24/2020', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 'http://dummyimage.com/100x100.png/dddddd/000000', '5/12/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (34, 1, 'Environmental Tech', 'Mino', 'Sedona', '$12060.76', '7/14/2021', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '9/5/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (35, 1, 'Project Manager', 'Kotkot', 'Suburban 1500', '$28978.04', '9/23/2021', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '9/7/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (36, 1, 'Analog Circuit Design manager', 'Danan', 'L300', '$22470.52', '4/21/2021', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '7/29/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (37, 1, 'Pharmacist', 'Akron', 'Passat', '$28572.62', '10/5/2020', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '5/8/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (38, 1, 'Programmer Analyst I', 'Yonggu', 'Tiburon', '$26637.22', '8/28/2021', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '9/11/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (39, 1, 'Nurse Practicioner', 'Rontu', 'H3', '$19475.71', '12/23/2020', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '10/28/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (40, 1, 'Project Manager', 'Osiek', 'Miata MX-5', '$17827.01', '9/11/2021', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'http://dummyimage.com/100x100.png/dddddd/000000', '10/22/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (41, 1, 'Clinical Specialist', 'Huoqiu Chengguanzhen', 'Outback', '$20931.64', '6/25/2021', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '2/16/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (42, 1, 'Paralegal', 'Penitik', 'CTS', '$14093.57', '9/29/2021', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'http://dummyimage.com/100x100.png/ff4444/ffffff', '9/14/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (43, 1, 'Marketing Manager', 'Rixi', 'Tacoma', '$13690.64', '1/3/2021', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '8/10/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (44, 1, 'Speech Pathologist', 'Dhuusamarreeb', '5 Series', '$26217.82', '6/30/2021', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 'http://dummyimage.com/100x100.png/cc0000/ffffff', '9/28/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (45, 1, 'Food Chemist', 'Zhutian', 'NSX', '$27593.78', '10/9/2020', 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '7/20/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (46, 1, 'Tax Accountant', 'Tangxi', 'Mustang', '$16002.12', '8/22/2021', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'http://dummyimage.com/100x100.png/dddddd/000000', '9/3/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (47, 1, 'Project Manager', 'Heshan', 'Ram Van 1500', '$22931.23', '3/24/2021', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'http://dummyimage.com/100x100.png/dddddd/000000', '4/9/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (48, 1, 'Accounting Assistant I', 'Néma', 'S60', '$10651.15', '4/15/2021', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'http://dummyimage.com/100x100.png/dddddd/000000', '2/22/2021');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (49, 1, 'Associate Professor', 'Gudang', 'Sierra 3500', '$23780.36', '4/22/2021', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '11/7/2020');
        insert into job (id, "companyProfileId", title, location, category, salary, "expDate", description, "imgUrl", "createdAt") values (50, 1, 'Recruiter', 'Sémbé', '80', '$28230.83', '6/25/2021', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '11/4/2020');
        `)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
